export const ROUTES = Object.freeze({
  HOME: '/',
  ZALO_CONNECTION: '/zalo/ket-noi',
  ZALO_INBOX: '/zalo/hop-thoai',
  LOGIN: '/dang-nhap',
  CHANGE_FIRST_PASSWORD: '/cap-nhat-mat-khau',
  SHOPS: '/cua-hang',
  CUSTOMERS: '/khach-hang',
  OPPORTUNITIES: '/co-hoi',
  OPPORTUNITIES_IMPORT: '/co-hoi/import',
  CUSTOMER_ASSIGNMENTS: '/theo-doi-phan-bo-khach-hang',
  STAFF_ASSIGNMENTS: '/theo-doi-phan-bo-nhan-vien',
  ORDERS: '/don-hang',
  PRODUCTS: '/san-pham',
  STAFF: '/nhan-vien',
  LOYALTY: '/loyalty',
  CARE_TODAY: '/kh-cham-soc-hom-nay',
  CARE_UPCOMING: '/lich-cham-soc-sap-dien-ra',
  CARE_OVERDUE: '/khach-cham-soc-qua-han',
  CARE_FIX_REQUESTS: '/yeu-cau-sua-cskh',
  PURCHASE_REGIONS: '/khu-vuc-mua-hang',
  PRODUCT_REPORT: '/bao-cao-san-pham',
  CUSTOMERS_UPGRADING: '/khach-hang-sap-thang-hang',
  LOYALTY_REPORT: '/bao-cao-loyalty',
  ORDER_REPORT: '/bao-cao-don-hang',
  CUSTOMER_REPORT: '/bao-cao-khach-hang',
  REVENUE: '/doanh-thu',
  GENERAL_SETTINGS: '/cai-dat-chung',
  ROLES: '/phan-quyen',
  WEBHOOK: '/webhook-url',
  PROFILE: '/ca-nhan',
  WEBHOOK_MONITOR: '/giam-sat-webhook',
  ACTIVITY_LOG: '/quan-ly-log',
})

export const ADMIN_ONLY_ROUTES = Object.freeze([
  ROUTES.ZALO_CONNECTION,
  ROUTES.REVENUE,
  ROUTES.PURCHASE_REGIONS,
  ROUTES.PRODUCT_REPORT,
  ROUTES.CUSTOMERS_UPGRADING,
  ROUTES.LOYALTY_REPORT,
  ROUTES.ORDER_REPORT,
  ROUTES.CUSTOMER_REPORT,
  ROUTES.WEBHOOK_MONITOR,
  ROUTES.ACTIVITY_LOG,
])

export const API_ROUTES = Object.freeze({
  LOGIN: '/auth/login',
  ME: '/me',
  LOGOUT: '/me/logout',
  CHANGE_FIRST_PASSWORD: '/change-first-password',
  SHOPS: '/shops',
  CUSTOMERS: '/customers',
  CUSTOMER_ORDER_INSIGHTS: '/customers/order-insights',
  CUSTOMER_ORDERS: (customerId) => `/customers/${customerId}/orders`,
  CUSTOMER_JOURNEY: (customerId) => `/customers/${customerId}/journey`,
  PRODUCTS: '/products',
  PRODUCT_SALES: '/products/sales',
  PRODUCT_PERIOD_REPORT: '/products/period-report',
  PRODUCT_MONTHLY_QUANTITIES: '/products/monthly-quantities',
  ORDERS: '/orders',
  ORDER_SALES_CHART: '/orders/sales-chart-data',
  ORDER_SOURCES: '/order-sources',
  ORDER_PAGES: '/order-pages',
  PROVINCES: '/provinces',
  PROVINCES_REPORT: '/provinces/report',
  PROVINCES_CHARTS: '/provinces/charts',  
  LOYALTY_TIERS: '/loyalty-tiers',
  ROLE_OPTIONS: '/roles/options',
  PERMISSION_GROUPS: '/permission-groups',
  PERMISSIONS: '/permissions',
  USERS_ALL: '/users/all-user',
  USER_MONITORING: '/users/mornitoring',
  USERS: '/users',
  ROLES: '/roles/options',
  ROLE_MANAGEMENT: '/roles',
  ROLE_PERMISSIONS: '/role-permissions',
  ACTIVITY_LOGS: '/activity-logs',
  CUSTOMER_CARES: '/customer-cares',
  ORDER_OPPORTUNITIES: '/orders/chance',
  IMPORTED_OPPORTUNITIES: '/imported-opportunities',
  IMPORTED_OPPORTUNITIES_TEMPLATE: '/imported-opportunities/template',
  IMPORTED_OPPORTUNITIES_IMPORT: '/imported-opportunities/import',
  IMPORTED_OPPORTUNITIES_ASSIGN: '/imported-opportunities/assign',
  OVERVIEW: '/overview',
  LOYALTY_OVERVIEW: '/loyalty-tiers/overview',
  LOYALTY_TOTAL_DISCOUNT: '/loyalty-tiers/total-discount',
  LOYALTY_UPGRADE_SUMMARY: '/loyalty-tiers/customers/pendding-upgrade',
  SETTINGS: '/settings',
})


